config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  post '/send_mail', to: "static_pages#send_mail"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  def home
  end

  def send_mail
    email = VALID_EMAIL_REGEX.match(params[:session][:email])
    if email.nil?
      flash[:danger] = "Invalid email address. Greeting mail has not been sent."
    else
      SampleMailer.greeting_mail(email).deliver_now
      flash[:success] = "Greeting mail has been successfully sent, please check your email."
    end

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Send Email</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome, Please enter your email address if you want us to send you a mail</h1>
<div class="col-md-6 col-md-offset-3">
<%= form_for(:session, url: send_mail_path) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.submit "Send me a mail", class: 'btn btn-primary' %>
<% end %>